AWSTemplateFormatVersion: 2010-09-09
Description: OIDC provider that lets GitHub Actions deploy to AWS

Parameters:
    FullRepoName:
        Type: String

Resources:
    Role:
        Type: AWS::IAM::Role
        Properties:
            RoleName: bref-layer-publisher-github-actions
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRoleWithWebIdentity
                      Principal:
                          Federated: !Ref GithubOidc
                      Condition:
                          StringLike:
                              token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*
            Policies:
                -   PolicyName: LayerPublisherRole
                    PolicyDocument:
                        Statement:
                            -   Effect: Allow
                                Action:
                                    - lambda:PublishLayerVersion
                                    - lambda:AddLayerVersionPermission
                                    - lambda:GetLayerVersion
                                    - lambda:GetLayerVersionPolicy
                                    - lambda:ListLayers
                                    - lambda:ListLayerVersions
                                Resource:
                                    - '*'

    GithubOidc:
        Type: AWS::IAM::OIDCProvider
        Properties:
            Url: https://token.actions.githubusercontent.com
            ThumbprintList:
                - '6938fd4d98bab03faadb97b34396831e3780aea1'
                - '1c58a3a8518e8759bf075b76b750d4f2df264fcd'
            ClientIdList:
                - sts.amazonaws.com

Outputs:
    Role:
        Value: !GetAtt Role.Arn
