check:
	php verify.php php-80/cpu-x86.Dockerfile
	php verify.php php-80/cpu-arm.Dockerfile
	php verify.php php-81/cpu-x86.Dockerfile
	php verify.php php-82/cpu-x86.Dockerfile

update:
	docker-compose run --rm update-list
